#!/bin/bash
echo "Деплой: загрузка проекта..."

cd ~/bots/RedCat-git \
&& git pull origin master \
&& echo "Деплой: установка зависимостей..." \
&& npm i \
&& echo "Деплой: перезагрузка проекта..." \
&& (pm2 reload 4 || true) \
&& echo "Деплой: успешно выполнено."
